version: '3'
services:
  guestbook-db:
    image: postgres:9.6.11
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_PASSWORD: password